Feat: support dependency parsing in cicd

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,20 +18,91 @@ jobs:
         uses: technote-space/get-diff-action@v6
     outputs:
       CHANGED_FILE: ${{ steps.diff.outputs.diff }}
-  structure-check:
+  deps:
     needs: diff
+    runs-on: ubuntu-latest
+    name: parse deps and get affected stacks/projecrs by diff files
+    container: 
+      image: kusionstack/kusionctl:latest
+      env: 
+        changePaths: ${{needs.diff.outputs.CHANGED_FILE}}
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+      - id: deps
+        shell: bash
+        run: |
+          echo "changed paths from git diff action: ${changePaths}"
+          echo "remove single quotes from changed paths"
+          changePaths=${changePaths//\'/}
+          echo "removed paths: ${changePaths}"
+
+          affected_stacks=""
+          affected_projs=""
+          deps_stack_exit_code=0
+          deps_proj_exit_code=0
+
+          # 1. check if the changed paths empty
+          if [ -z "${changePaths}" ]; then
+            # got empty change paths:
+            echo "got empty changed paths, not deps will be tested"
+          else
+            # 2. parse and get affected stacks and projects
+
+            # 2.1 convert change paths to --focus option
+            change_paths_array=$(echo "$changePaths" | tr '\n' ' ')
+            focus_files=$(printf -- "--focus %s " $change_paths_array)
+            
+            # 2.2 execute deps command
+
+            # affected stacks
+            deps_cmd_stack="kusion deps --direct down --only stack $focus_files"
+            echo "get affected stacks: running cmd: $deps_cmd_stack"
+            affected_stacks=$($deps_cmd_stack)
+            deps_stack_exit_code=$?
+
+            # affected projects
+            deps_cmd_proj="kusion deps --direct down $focus_files"
+            echo "get affected projects: running cmd: $deps_cmd_proj"
+            affected_projs=$($deps_cmd_proj)
+            deps_proj_exit_code=$?
+          fi
+
+          # 3. set output
+          echo "affected stacks: $affected_stacks"
+          echo "affected projects: $affected_projs"
+          # escape the newline symbol in the results:
+          affected_stacks="${affected_stacks//$'\n'/'%0A'}"
+          affected_projs="${affected_projs//$'\n'/'%0A'}"
+          echo "::set-output name=affected_stacks::$affected_stacks"
+          echo "::set-output name=affected_projs::$affected_projs"
+
+          # 4. If deps cli failed, exit with the actual exit code
+          [ $deps_stack_exit_code -eq 0 ] && echo "deps command --only stack was successful" || exit "deps command --only stack failed"
+          [ $deps_proj_exit_code -eq 0 ] && echo "deps command --only project was successful" || exit "deps command --only project failed"
+      - name: get output result
+        run: |
+          echo "affected stacks: ${{ steps.deps.outputs.affected_stacks }}"
+          echo "affected projects: ${{ steps.deps.outputs.affected_projs }}"
+    outputs:
+      affected_stacks: ${{ steps.deps.outputs.affected_stacks }}
+      affected_projs: ${{ steps.deps.outputs.affected_projs }}
+  structure-check:
+    needs: deps
     runs-on: ubuntu-latest
     container: 
       image: kusionstack/kusion:latest
       env: 
         CHANGED_FILE: ${{needs.diff.outputs.CHANGED_FILE}}
+        AFFECTED_STACKS: ${{needs.deps.outputs.affected_stacks}}
+        AFFECTED_PROJECTS: ${{needs.deps.outputs.affected_projs}}
     steps:
       - uses: actions/checkout@v2
       - id: install-pytest-html
         run: kclvm -mpip install pytest-html -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
       - id: structure-check
-        run: |
-          kclvm -mpytest -v hack/verify-project-structure.py --junitxml ./hack/report/TEST-structure.xml --html=./hack/report/structure.html
+        run: kclvm -mpytest -v hack/verify-project-structure.py --junitxml ./hack/report/TEST-structure.xml --html=./hack/report/structure.html
       - id: upload-structure-check-report
         if: always()
         uses: actions/upload-artifact@v2
@@ -40,55 +111,32 @@ jobs:
           path: |
             hack/report/TEST-structure.xml
             hack/report/structure.html
-  base-test:
-    needs: diff
+  test:
+    needs: deps
     runs-on: ubuntu-latest
     container: 
       image: kusionstack/kusion:latest
       env: 
         CHANGED_FILE: ${{needs.diff.outputs.CHANGED_FILE}}
+        AFFECTED_STACKS: ${{needs.deps.outputs.affected_stacks}}
+        AFFECTED_PROJECTS: ${{needs.deps.outputs.affected_projs}}
     steps:
       - uses: actions/checkout@v2
       - id: install-pytest-html
         run: kclvm -mpip install pytest-html -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
-      - id: base-test
-        run: |
-          export KCL_TEST_MODE="base"
-          kclvm -mpytest -v -n 5 hack/test_konfig.py --junitxml ./hack/report/TEST-base.xml --html=./hack/report/base.html
-      - id: upload-base-test-report
+      - id: test
+        run: kclvm -mpytest -v -n 5 hack/test_konfig.py --junitxml ./hack/report/TEST.xml --html=./hack/report/test.html
+      - id: upload-test-report
         if: always()
         uses: actions/upload-artifact@v2
         with:
-          name: base-test-report
+          name: test-report
           path: |
-            hack/report/TEST-base.xml
-            hack/report/base.html
-  biz-test:
-    needs: diff
-    runs-on: ubuntu-latest
-    container: 
-      image: kusionstack/kusion:latest
-      env: 
-        CHANGED_FILE: ${{needs.diff.outputs.CHANGED_FILE}}
-    steps:
-      - uses: actions/checkout@v2
-      - id: install-pytest-html
-        run: kclvm -mpip install pytest-html -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
-      - id: biz-test
-        run: |
-          export KCL_TEST_MODE="biz"
-          kclvm -mpytest -v -n 5 hack/test_konfig.py --junitxml ./hack/report/TEST-biz.xml --html=./hack/report/biz.html
-      - id: upload-biz-test-report
-        if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: biz-test-report
-          path: |
-            hack/report/TEST-biz.xml
-            hack/report/biz.html
+            hack/report/TEST.xml
+            hack/report/test.html
   apply:
     if: github.ref == 'refs/heads/main'
-    needs: [diff, structure-check, base-test, biz-test]
+    needs: [diff, deps, test]
     runs-on: ubuntu-latest 
     steps:
       - uses: actions/checkout@v2
